apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-worker-rolebinding
  namespace: jenkins-workers
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: jenkins-workers
roleRef:
  kind: Role
  name: jenkins-worker-role
  apiGroup: rbac.authorization.k8s.io
