apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-worker-secret-rolebinding
  namespace: default  # 🔹 Must match the secret's namespace
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: jenkins-workers  # 🔹 This must match your worker pod's ServiceAccount
roleRef:
  kind: Role
  name: jenkins-worker-secret-access
  apiGroup: rbac.authorization.k8s.io
