apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: ${CLUSTER_NAME}
servers: 1
agents: 2
ports:
  - port: 80:80      
    nodeFilters:
      - loadbalancer
  - port: 443:443    
    nodeFilters:
      - loadbalancer
  - port: 9000:9000 
    nodeFilters:
      - loadbalancer
