apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-secret-reader
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-secret-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default  
    namespace: jenkins
roleRef:
  kind: Role
  name: jenkins-secret-reader
  apiGroup: rbac.authorization.k8s.io
