apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: default
type: Opaque
data:
  postgres-user: cG9zdGdyZXM=       # Base64 encoded: "postgres"
  postgres-password: c2VjdXJlUGFzcw== # Base64 encoded: "securePass"
  postgres-db: ZGV2b3Bz               # Base64 encoded: "devops"