deployment:
  replicas: 2

ingressRoute:
  dashboard:
    enabled: true

ports:
  web:
    port: 80
    expose:
      enabled: true
    exposedPort: 80
    protocol: TCP

  websecure:
    port: 443
    expose:
      enabled: true
    exposedPort: 443
    protocol: TCP

  traefik:
    port: 9000
    expose:
      enabled: true
    exposedPort: 9000
    protocol: TCP

service:
  type: LoadBalancer
  ports:
    web: 80
    websecure: 443
    traefik: 9000

additionalArguments:
  - "--api.insecure=true"
  - "--api.dashboard=true"
  - "--entrypoints.traefik.address=:9000"
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
